services:
  - type: web
    name: waze-incidents
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python run.py
    envVars:
      - key: PORT
        value: 8000
      - key: WAZE_API_URL
        fromService:
          name: waze-incidents
          type: web
          property: env.WAZE_API_URL

